# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivers.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdrivers.proto\x12\x07\x64rivers\"g\n\x15RegisterDriverRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x0clicense_type\x18\x02 \x01(\x0e\x32\x14.drivers.LicenseType\x12\x14\n\x0c\x61vailability\x18\x03 \x01(\x08\"\x1e\n\x10GetDriverRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x88\x01\n\x12ListDriversRequest\x12\x16\n\x0c\x61vailability\x18\x01 \x01(\x08H\x00\x12,\n\x0clicense_type\x18\x02 \x01(\x0e\x32\x14.drivers.LicenseTypeH\x01\x42\x15\n\x13\x61vailability_filterB\x15\n\x13license_type_filter\"q\n\x13UpdateDriverRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x0clicense_type\x18\x03 \x01(\x0e\x32\x14.drivers.LicenseType\x12\x14\n\x0c\x61vailability\x18\x04 \x01(\x08\"N\n\x13\x41ssignDriverRequest\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x10\n\x08route_id\x18\x02 \x01(\t\x12\x12\n\nvehicle_id\x18\x03 \x01(\t\"\x80\x01\n\x0e\x44riverResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12*\n\x0clicense_type\x18\x03 \x01(\x0e\x32\x14.drivers.LicenseType\x12\x14\n\x0c\x61vailability\x18\x04 \x01(\x08\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"?\n\x13ListDriversResponse\x12(\n\x07\x64rivers\x18\x01 \x03(\x0b\x32\x17.drivers.DriverResponse\"8\n\x14\x41ssignDriverResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*-\n\x0bLicenseType\x12\t\n\x05Light\x10\x00\x12\t\n\x05Heavy\x10\x01\x12\x08\n\x04\x42oth\x10\x02\x32\xf9\x02\n\rDriverService\x12I\n\x0eRegisterDriver\x12\x1e.drivers.RegisterDriverRequest\x1a\x17.drivers.DriverResponse\x12?\n\tGetDriver\x12\x19.drivers.GetDriverRequest\x1a\x17.drivers.DriverResponse\x12H\n\x0bListDrivers\x12\x1b.drivers.ListDriversRequest\x1a\x1c.drivers.ListDriversResponse\x12\x45\n\x0cUpdateDriver\x12\x1c.drivers.UpdateDriverRequest\x1a\x17.drivers.DriverResponse\x12K\n\x0c\x41ssignDriver\x12\x1c.drivers.AssignDriverRequest\x1a\x1d.drivers.AssignDriverResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drivers_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LICENSETYPE']._serialized_start=751
  _globals['_LICENSETYPE']._serialized_end=796
  _globals['_REGISTERDRIVERREQUEST']._serialized_start=26
  _globals['_REGISTERDRIVERREQUEST']._serialized_end=129
  _globals['_GETDRIVERREQUEST']._serialized_start=131
  _globals['_GETDRIVERREQUEST']._serialized_end=161
  _globals['_LISTDRIVERSREQUEST']._serialized_start=164
  _globals['_LISTDRIVERSREQUEST']._serialized_end=300
  _globals['_UPDATEDRIVERREQUEST']._serialized_start=302
  _globals['_UPDATEDRIVERREQUEST']._serialized_end=415
  _globals['_ASSIGNDRIVERREQUEST']._serialized_start=417
  _globals['_ASSIGNDRIVERREQUEST']._serialized_end=495
  _globals['_DRIVERRESPONSE']._serialized_start=498
  _globals['_DRIVERRESPONSE']._serialized_end=626
  _globals['_LISTDRIVERSRESPONSE']._serialized_start=628
  _globals['_LISTDRIVERSRESPONSE']._serialized_end=691
  _globals['_ASSIGNDRIVERRESPONSE']._serialized_start=693
  _globals['_ASSIGNDRIVERRESPONSE']._serialized_end=749
  _globals['_DRIVERSERVICE']._serialized_start=799
  _globals['_DRIVERSERVICE']._serialized_end=1176
# @@protoc_insertion_point(module_scope)
