# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicles.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evehicles.proto\x12\x08vehicles\"_\n\x14\x43reateVehicleRequest\x12\r\n\x05plate\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05\x62rand\x18\x03 \x01(\t\x12\r\n\x05model\x18\x04 \x01(\t\x12\x0c\n\x04year\x18\x05 \x01(\x05\"\x1f\n\x11GetVehicleRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x13ListVehiclesRequest\x12\x13\n\x0btype_filter\x18\x01 \x01(\t\x12\x15\n\rstatus_filter\x18\x02 \x01(\t\"=\n\x13UpdateStatusRequest\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x12\n\nnew_status\x18\x02 \x01(\t\"<\n\x13\x41ssignDriverRequest\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\x12\x11\n\tdriver_id\x18\x02 \x01(\t\")\n\x13RemoveDriverRequest\x12\x12\n\nvehicle_id\x18\x01 \x01(\t\"\xa8\x01\n\x0fVehicleResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05plate\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\r\n\x05\x62rand\x18\x05 \x01(\t\x12\r\n\x05model\x18\x06 \x01(\t\x12\x0c\n\x04year\x18\x07 \x01(\x05\x12\x1c\n\x0f\x61ssigned_driver\x18\x08 \x01(\tH\x00\x88\x01\x01\x42\x12\n\x10_assigned_driver\"C\n\x14ListVehiclesResponse\x12+\n\x08vehicles\x18\x01 \x03(\x0b\x32\x19.vehicles.VehicleResponse2\xd7\x03\n\x0fVehiclesService\x12J\n\rCreateVehicle\x12\x1e.vehicles.CreateVehicleRequest\x1a\x19.vehicles.VehicleResponse\x12\x44\n\nGetVehicle\x12\x1b.vehicles.GetVehicleRequest\x1a\x19.vehicles.VehicleResponse\x12M\n\x0cListVehicles\x12\x1d.vehicles.ListVehiclesRequest\x1a\x1e.vehicles.ListVehiclesResponse\x12O\n\x13UpdateVehicleStatus\x12\x1d.vehicles.UpdateStatusRequest\x1a\x19.vehicles.VehicleResponse\x12H\n\x0c\x41ssignDriver\x12\x1d.vehicles.AssignDriverRequest\x1a\x19.vehicles.VehicleResponse\x12H\n\x0cRemoveDriver\x12\x1d.vehicles.RemoveDriverRequest\x1a\x19.vehicles.VehicleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicles_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEVEHICLEREQUEST']._serialized_start=28
  _globals['_CREATEVEHICLEREQUEST']._serialized_end=123
  _globals['_GETVEHICLEREQUEST']._serialized_start=125
  _globals['_GETVEHICLEREQUEST']._serialized_end=156
  _globals['_LISTVEHICLESREQUEST']._serialized_start=158
  _globals['_LISTVEHICLESREQUEST']._serialized_end=223
  _globals['_UPDATESTATUSREQUEST']._serialized_start=225
  _globals['_UPDATESTATUSREQUEST']._serialized_end=286
  _globals['_ASSIGNDRIVERREQUEST']._serialized_start=288
  _globals['_ASSIGNDRIVERREQUEST']._serialized_end=348
  _globals['_REMOVEDRIVERREQUEST']._serialized_start=350
  _globals['_REMOVEDRIVERREQUEST']._serialized_end=391
  _globals['_VEHICLERESPONSE']._serialized_start=394
  _globals['_VEHICLERESPONSE']._serialized_end=562
  _globals['_LISTVEHICLESRESPONSE']._serialized_start=564
  _globals['_LISTVEHICLESRESPONSE']._serialized_end=631
  _globals['_VEHICLESSERVICE']._serialized_start=634
  _globals['_VEHICLESSERVICE']._serialized_end=1105
# @@protoc_insertion_point(module_scope)
