# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fuel.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfuel.proto\x12\x04\x66uel\"[\n\x1eRegisterFuelConsumptionRequest\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x12\n\nvehicle_id\x18\x02 \x01(\t\x12\x13\n\x0b\x66uel_amount\x18\x03 \x01(\x01\"\'\n\x19GetFuelConsumptionRequest\x12\n\n\x02id\x18\x01 \x01(\t\"Y\n\x1bListFuelConsumptionsRequest\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x12\n\nvehicle_id\x18\x02 \x01(\t\x12\x14\n\x0cvehicle_type\x18\x03 \x01(\t\"t\n\x17\x46uelConsumptionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08route_id\x18\x02 \x01(\t\x12\x12\n\nvehicle_id\x18\x03 \x01(\t\x12\x13\n\x0b\x66uel_amount\x18\x04 \x01(\x01\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"S\n\x1cListFuelConsumptionsResponse\x12\x33\n\x0c\x63onsumptions\x18\x01 \x03(\x0b\x32\x1d.fuel.FuelConsumptionResponse\"2\n\x1aReportByVehicleTypeRequest\x12\x14\n\x0cvehicle_type\x18\x01 \x01(\t\"u\n\x1bReportByVehicleTypeResponse\x12\x12\n\ntotal_fuel\x18\x01 \x01(\x01\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x33\n\x0c\x63onsumptions\x18\x03 \x03(\x0b\x32\x1d.fuel.FuelConsumptionResponse\"1\n\x1d\x43ompareEstimatedVsRealRequest\x12\x10\n\x08route_id\x18\x01 \x01(\t\"O\n\x1e\x43ompareEstimatedVsRealResponse\x12\x11\n\testimated\x18\x01 \x01(\x01\x12\x0c\n\x04real\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t2\xe3\x03\n\x0b\x46uelService\x12^\n\x17RegisterFuelConsumption\x12$.fuel.RegisterFuelConsumptionRequest\x1a\x1d.fuel.FuelConsumptionResponse\x12T\n\x12GetFuelConsumption\x12\x1f.fuel.GetFuelConsumptionRequest\x1a\x1d.fuel.FuelConsumptionResponse\x12]\n\x14ListFuelConsumptions\x12!.fuel.ListFuelConsumptionsRequest\x1a\".fuel.ListFuelConsumptionsResponse\x12Z\n\x13ReportByVehicleType\x12 .fuel.ReportByVehicleTypeRequest\x1a!.fuel.ReportByVehicleTypeResponse\x12\x63\n\x16\x43ompareEstimatedVsReal\x12#.fuel.CompareEstimatedVsRealRequest\x1a$.fuel.CompareEstimatedVsRealResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fuel_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTERFUELCONSUMPTIONREQUEST']._serialized_start=20
  _globals['_REGISTERFUELCONSUMPTIONREQUEST']._serialized_end=111
  _globals['_GETFUELCONSUMPTIONREQUEST']._serialized_start=113
  _globals['_GETFUELCONSUMPTIONREQUEST']._serialized_end=152
  _globals['_LISTFUELCONSUMPTIONSREQUEST']._serialized_start=154
  _globals['_LISTFUELCONSUMPTIONSREQUEST']._serialized_end=243
  _globals['_FUELCONSUMPTIONRESPONSE']._serialized_start=245
  _globals['_FUELCONSUMPTIONRESPONSE']._serialized_end=361
  _globals['_LISTFUELCONSUMPTIONSRESPONSE']._serialized_start=363
  _globals['_LISTFUELCONSUMPTIONSRESPONSE']._serialized_end=446
  _globals['_REPORTBYVEHICLETYPEREQUEST']._serialized_start=448
  _globals['_REPORTBYVEHICLETYPEREQUEST']._serialized_end=498
  _globals['_REPORTBYVEHICLETYPERESPONSE']._serialized_start=500
  _globals['_REPORTBYVEHICLETYPERESPONSE']._serialized_end=617
  _globals['_COMPAREESTIMATEDVSREALREQUEST']._serialized_start=619
  _globals['_COMPAREESTIMATEDVSREALREQUEST']._serialized_end=668
  _globals['_COMPAREESTIMATEDVSREALRESPONSE']._serialized_start=670
  _globals['_COMPAREESTIMATEDVSREALRESPONSE']._serialized_end=749
  _globals['_FUELSERVICE']._serialized_start=752
  _globals['_FUELSERVICE']._serialized_end=1235
# @@protoc_insertion_point(module_scope)
