name: Docker Image Build

on:
  schedule:
    # Build nightly para detectar problemas temprano
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build-matrix:
    name: Build All Services
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - auth-service
          - vehicle-service
          - route-service
          - fuel-consumption-service
          - driver-service
          - api-gateway
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: false
          tags: xyz-${{ matrix.service }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image
        run: |
          docker images | grep xyz-${{ matrix.service }}
